/** @jsxImportSource preact */
import { useEffect, useState } from 'preact/hooks';
import type { ComponentChildren } from 'preact';
import { useSetupTwoFactor, useEnableTwoFactor } from '../../actions.js';
import type { AuthClient } from '../../../../core/auth-client.js';

/**
 * TOTP enrollment wizard. Two visual steps:
 *
 *   1. Enroll — calls `setupTwoFactor`, shows the provisioning URI
 *      (rendered as a QR code via a quick external charts service)
 *      and the base32 secret as a fallback for users without a QR
 *      scanner.
 *
 *   2. Confirm — collects the first 6-digit code from the
 *      authenticator app and calls `enableTwoFactor`. The server
 *      stamps `two_factor_confirmed_at` only after a valid code,
 *      so this step is required (skipping it = "setup but not
 *      enforced" state, harmless but useless).
 *
 * The QR code is generated by Google Chart API as a tiny static URL —
 * no client-side QR library dependency. Swap by passing `renderQr`.
 */
export interface TwoFactorEnrollmentProps {
    client?: AuthClient;
    /** Custom QR renderer; receives the otpauth:// URI. */
    renderQr?: (uri: string) => ComponentChildren;
    onComplete?: () => void;
    className?: string;
}

function defaultQr(uri: string): ComponentChildren {
    const src = `https://api.qrserver.com/v1/create-qr-code/?size=180x180&data=${encodeURIComponent(uri)}`;
    return <img src={src} width="180" height="180" alt="Scan with your authenticator app" />;
}

export function TwoFactorEnrollment(props: TwoFactorEnrollmentProps) {
    const setup = useSetupTwoFactor(props.client);
    const enable = useEnableTwoFactor(props.client);
    const [code, setCode] = useState('');
    const [completed, setCompleted] = useState(false);

    // Auto-start setup on mount — most users land on this page to set
    // up 2FA right then. Skip if already enrolling (e.g. re-mount).
    useEffect(() => {
        if (setup.isIdle && !setup.loading && !setup.data) {
            void setup.run();
        }
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, []);

    const onConfirm = async (e: Event) => {
        e.preventDefault();
        await enable.run(code);
        setCompleted(true);
        props.onComplete?.();
    };

    if (completed) {
        return (
            <div class={`vauth-form-success ${props.className ?? ''}`} role="status">
                Two-factor authentication enabled. You'll be asked for a code at next sign-in.
            </div>
        );
    }

    if (setup.loading || !setup.data) {
        return <div class={`vauth-form-loading ${props.className ?? ''}`}>Generating secret…</div>;
    }

    const { secret, provisioningUri } = setup.data;
    const renderQr = props.renderQr ?? defaultQr;
    return (
        <div class={`vauth-form vauth-2fa-enroll ${props.className ?? ''}`}>
            <ol class="vauth-2fa-steps">
                <li>
                    <h4>1. Scan with your authenticator app</h4>
                    <div class="vauth-2fa-qr">{renderQr(provisioningUri)}</div>
                    <details>
                        <summary>Can't scan? Enter this code manually</summary>
                        <pre class="vauth-2fa-secret">{secret}</pre>
                    </details>
                </li>
                <li>
                    <h4>2. Enter the 6-digit code your app shows</h4>
                    <form onSubmit={onConfirm}>
                        <input
                            class="vauth-input vauth-2fa-code-input"
                            type="text"
                            inputMode="numeric"
                            pattern="[0-9]*"
                            maxLength={6}
                            autoComplete="one-time-code"
                            value={code}
                            onInput={(e) => setCode((e.target as HTMLInputElement).value)}
                            disabled={enable.loading}
                            required
                            autoFocus
                        />
                        {enable.error && <div class="vauth-error" role="alert">{enable.error.message}</div>}
                        <button
                            type="submit"
                            class="vauth-btn vauth-btn-primary"
                            disabled={enable.loading || code.length !== 6}
                            aria-busy={enable.loading}
                        >
                            {enable.loading ? 'Verifying…' : 'Confirm and enable'}
                        </button>
                    </form>
                </li>
            </ol>
        </div>
    );
}
